# Generated by Django 3.1.4 on 2021-05-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiretuber',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hiretuber',
            name='last_name',
        ),
    ]
