# Generated by Django 3.2 on 2021-04-11 13:22

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=True)),
                ('subtitle', models.CharField(max_length=255)),
                ('bottom_text', models.CharField(max_length=255)),
            ],
        ),
    ]
