# Generated by Django 3.2 on 2021-04-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_rename_title_slider_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='bottom_text',
            new_name='button_text',
        ),
    ]
