# Generated by Django 3.2 on 2021-04-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='headline',
        ),
    ]
