# Generated by Django 3.2 on 2021-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='yt_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
